"""64 char email

Revision ID: 17b8fb69fc1
Revises: 4890345f468
Create Date: 2015-07-29 16:47:07.884363

"""

# revision identifiers, used by Alembic.
revision = '17b8fb69fc1'
down_revision = '4890345f468'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
