"""registration confirmation tokens

Revision ID: 182b6f3f375
Revises: 574b4793e8e
Create Date: 2015-07-29 00:17:05.239399

"""

# revision identifiers, used by Alembic.
revision = '182b6f3f375'
down_revision = '574b4793e8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
