"""cache gravatar hashed

Revision ID: 56bc666ff2f
Revises: 130238aa1c0
Create Date: 2015-07-29 17:55:35.559808

"""

# revision identifiers, used by Alembic.
revision = '56bc666ff2f'
down_revision = '130238aa1c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
