"""Post body_html

Revision ID: 5a9d0f7ecca
Revises: 3a7ec0cd7b2
Create Date: 2015-07-29 22:31:22.254000

"""

# revision identifiers, used by Alembic.
revision = '5a9d0f7ecca'
down_revision = '3a7ec0cd7b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
